/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.dainamic.nepum.ui.admin;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import pt.dainamic.nepum.model.Admin;
import pt.dainamic.nepum.ws.AdminWS;
import sun.misc.BASE64Encoder;

/**
 *
 * @author jorge
 */
public class AdminProfileEdit extends javax.swing.JFrame {

    private Logger log = Logger.getLogger(AdminProfile.class);
    private Admin ad;
    private BufferedImage pic = null;

    /**
     * Creates new form AdminProfileEdit
     */
    public AdminProfileEdit(Admin ad) {
        initComponents();
        setIcon();
        this.ad = ad;
        try {
            setFields(this.ad);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(AdminProfileEdit.this,
                    e.getMessage(), "Erro ao carregar o seu perfil", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserPhoto = new javax.swing.JFileChooser();
        jPanelWallpaper = new javax.swing.JPanel();
        jPanelInformation = new javax.swing.JPanel();
        jLabelProfile = new javax.swing.JLabel();
        jLabelPhoto = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelBirthDate = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jLabelCC = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelNationality = new javax.swing.JLabel();
        jLabelAdress = new javax.swing.JLabel();
        jButtonEditProfile = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldNTel = new javax.swing.JTextField();
        jTextFieldNCC = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jTextFieldNationality = new javax.swing.JTextField();
        jTextFieldAdress = new javax.swing.JTextField();
        jButtonEditPhoto = new javax.swing.JButton();
        jDateChooserBirthDate = new com.toedter.calendar.JDateChooser();
        jComboBoxBloodType = new javax.swing.JComboBox();
        jLabelInformation = new javax.swing.JLabel();
        jLabelwallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(705, 520));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelWallpaper.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanelWallpaper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInformation.setMaximumSize(new java.awt.Dimension(680, 380));
        jPanelInformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelProfile.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelProfile.setText("Editar Administrador");
        jPanelInformation.add(jLabelProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabelPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/dainamic/nepum/images/pics/profile.PNG"))); // NOI18N
        jPanelInformation.add(jLabelPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 80));

        jLabelName.setText("Nome:");
        jPanelInformation.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 49, 40, 20));

        jLabelBirthDate.setText("   Data de nascimento:");
        jPanelInformation.add(jLabelBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 120, 20));

        jLabelTel.setText("  Nº Tel.:");
        jPanelInformation.add(jLabelTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 50, 20));

        jLabelCC.setText(" Nº CC:");
        jPanelInformation.add(jLabelCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 50, 20));

        jLabelEmail.setText("   Email:");
        jPanelInformation.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 140, 50, 20));

        jLabelLastName.setText("    Apelido:");
        jPanelInformation.add(jLabelLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 60, 20));

        jLabelGender.setText("Grupo Sanguíneo:");
        jPanelInformation.add(jLabelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 100, 40));

        jLabelNationality.setText("   Nacionalidade:");
        jPanelInformation.add(jLabelNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 90, 20));

        jLabelAdress.setText("Morada:");
        jPanelInformation.add(jLabelAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, 20));

        jButtonEditProfile.setText("Submeter Alterações");
        jButtonEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditProfileActionPerformed(evt);
            }
        });
        jPanelInformation.add(jButtonEditProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        jButtonBack.setText("Voltar");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanelInformation.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyTyped(evt);
            }
        });
        jPanelInformation.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 170, -1));
        jPanelInformation.add(jTextFieldNTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 170, -1));
        jPanelInformation.add(jTextFieldNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 160, -1));
        jPanelInformation.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 200, -1));

        jTextFieldLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLastNameKeyTyped(evt);
            }
        });
        jPanelInformation.add(jTextFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 160, -1));

        jTextFieldNationality.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNationalityKeyTyped(evt);
            }
        });
        jPanelInformation.add(jTextFieldNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 160, -1));
        jPanelInformation.add(jTextFieldAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 440, -1));

        jButtonEditPhoto.setText("Alterar Foto");
        jButtonEditPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPhotoActionPerformed(evt);
            }
        });
        jPanelInformation.add(jButtonEditPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanelInformation.add(jDateChooserBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 170, -1));

        jComboBoxBloodType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        jPanelInformation.add(jComboBoxBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 60, -1));

        jLabelInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/dainamic/nepum/images/backGround/second.jpg"))); // NOI18N
        jLabelInformation.setMaximumSize(new java.awt.Dimension(680, 380));
        jLabelInformation.setMinimumSize(new java.awt.Dimension(680, 380));
        jLabelInformation.setPreferredSize(new java.awt.Dimension(680, 380));
        jPanelInformation.add(jLabelInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelWallpaper.add(jPanelInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 680, 380));

        jLabelwallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/dainamic/nepum/images/backGround/first.jpg"))); // NOI18N
        jPanelWallpaper.add(jLabelwallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditProfileActionPerformed
        try {

            AdminWS adWS = new AdminWS();
            adWS.editAdmin(loadAdminFromPanel());
            new AdminProfile(ad.getIdAdmin()).setVisible(true);
            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(AdminProfileEdit.this,
                    e.getMessage(), "Erro ao editar perfil", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEditProfileActionPerformed


    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        new AdminProfile(ad.getIdAdmin()).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonEditPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPhotoActionPerformed
        jFileChooserPhoto.showOpenDialog(this);
        File f = jFileChooserPhoto.getSelectedFile();
        try {
            ImageIcon image = new ImageIcon(f.getAbsolutePath());
            jLabelPhoto.setIcon(new ImageIcon(image.getImage().getScaledInstance(
                    jLabelPhoto.getWidth(), jLabelPhoto.getHeight(), Image.SCALE_DEFAULT)));
            pic = ImageIO.read(f);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(AdminProfileEdit.this,
                    "Erro ao carregar imagem", "Erro ao editar Administrador",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonEditPhotoActionPerformed

    private void jTextFieldNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyTyped
        numberConsume(evt);
    }//GEN-LAST:event_jTextFieldNameKeyTyped

    private void jTextFieldLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLastNameKeyTyped
        numberConsume(evt);
    }//GEN-LAST:event_jTextFieldLastNameKeyTyped

    private void jTextFieldNationalityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNationalityKeyTyped
        numberConsume(evt);

    }//GEN-LAST:event_jTextFieldNationalityKeyTyped
    private void numberConsume(KeyEvent evt) {
        String numbers = "0123456789";
        if (numbers.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }

    private void setIcon() {
        List<Image> icons = new ArrayList<>();
        icons.add(new ImageIcon(getClass().getResource("/pt/dainamic/nepum/images/logo.png")).getImage());
        icons.add(new ImageIcon(getClass().getResource("/pt/dainamic/nepum/images/logo-icon.png")).getImage());
        setIconImages(icons);
    }

    private void setFields(Admin a) {
        this.jTextFieldName.setText(a.getName());
        this.jTextFieldLastName.setText(a.getLastName());
        this.jDateChooserBirthDate.setDate(dateParse(a.getBirthDate()));
        this.jTextFieldNTel.setText(String.valueOf(a.getNumTel()));
        this.jTextFieldNationality.setText(a.getNationality());
        this.jTextFieldNCC.setText(String.valueOf(a.getNumCC()));
        this.jTextFieldEmail.setText(a.getEmail());
        this.jTextFieldAdress.setText(a.getAdress());
        this.jComboBoxBloodType.setSelectedItem(a.getBloodGroup());

        if (a.getPicture().equals("profile")) {
            ImageIcon pic = new ImageIcon(getClass().getResource("/pt/dainamic/nepum/images/pics/profile.PNG"));
            jLabelPhoto.setIcon(new ImageIcon(pic.getImage().getScaledInstance(
                    jLabelPhoto.getWidth(), jLabelPhoto.getHeight(), Image.SCALE_DEFAULT)));
        } else {
            jLabelPhoto.setIcon(new ImageIcon(getImageFromServer(a.getPicture(), 90, 90)));
        }

    }

    private String validator() {
        StringBuilder warns = new StringBuilder();
        warns.append(jTextFieldName.getText().isEmpty() ? "Nome, " : "");
        warns.append(jTextFieldLastName.getText().isEmpty() ? "Apelido, " : "");
        warns.append(jDateChooserBirthDate.getDate().toString().isEmpty() ? "Data de Nascimento, " : "");
        warns.append(jTextFieldNCC.getText().isEmpty() ? "Numero CC, " : "");
        warns.append(jTextFieldEmail.getText().isEmpty() ? "E-mail, " : "");
        warns.append(jTextFieldNTel.getText().trim().isEmpty() ? "Número de Telemóvel, " : "");
        if (!warns.toString().isEmpty()) {
            warns.delete(warns.toString().length() - 2, warns.toString().length());
            warns.append("!");
        }

        return warns.toString();
    }

    private Admin loadAdminFromPanel() {
        String warn = validator();
        if (!warn.isEmpty()) {
            throw new RuntimeException("Preencha o(s) seguintes dado(s): " + warn);
        }
        String name = jTextFieldName.getText();
        ad.setName(name);
        String lastName = jTextFieldLastName.getText();
        ad.setLastName(lastName);
        String email = jTextFieldEmail.getText().trim();
        ad.setEmail(email);
        String adress = jTextFieldAdress.getText();
        ad.setAdress(adress);
        String nationality = jTextFieldNationality.getText();
        ad.setNationality(nationality);
        String bloodGroup = String.valueOf(jComboBoxBloodType.getSelectedItem());
        ad.setBloodGroup(bloodGroup);
        Date birthDate = jDateChooserBirthDate.getDate();
        ad.setBirthDate(parseDate(birthDate));
        int numTel = 0;
        int numCC = 0;
        try {
            if (jTextFieldNTel.getText().trim().length() != 9) {
                throw new RuntimeException("O NºTel deve ter 9 digitos!");
            }
            if (jTextFieldNCC.getText().trim().length() != 8) {
                throw new RuntimeException("O NºCC deve ter 8 digitos!");
            }
            numTel = Integer.valueOf(jTextFieldNTel.getText().trim());
            ad.setNumTel(numTel);
            numCC = Integer.valueOf(jTextFieldNCC.getText().trim());
            ad.setNumCC(numCC);

        } catch (NumberFormatException e) {
            throw new RuntimeException("Apenas numeros são permitidos nos campos NºTel e NºCC");
        } catch (RuntimeException e) {
            throw new RuntimeException(e.getMessage());
        }

        ad.setPicture(encodeToString(pic, "jpg"));

        return ad;
    }

    private Image getImageFromServer(String picture, int with, int heigth) {
        try {
            URL url = new URL(picture.trim());
            log.debug("\n\tProfile Image: " + url.toString());
            BufferedImage image = ImageIO.read(url);
            ImageIcon pic = new ImageIcon(image);
            return pic.getImage().getScaledInstance(with, heigth, Image.SCALE_DEFAULT);
        } catch (MalformedURLException ex) {
            log.error(ex.getMessage());
            throw new RuntimeException("Erro ao carregar imagem");
        } catch (IOException ex) {
            log.error(ex.getMessage());
            throw new RuntimeException("Erro ao carregar imagem");
        }
    }

    public String parseDate(Date d) {
        SimpleDateFormat dateFromat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFromat.format(d);
        return date;
    }

    private String encodeToString(BufferedImage image, String type) {
        if (image == null) {
            return "profile";
        }

        String imageString = null;
        ByteArrayOutputStream bos = new ByteArrayOutputStream();

        try {
            ImageIO.write(image, type, bos);
            byte[] imageBytes = bos.toByteArray();

            BASE64Encoder encoder = new BASE64Encoder();
            imageString = encoder.encode(imageBytes);

            bos.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return imageString;
    }

    private Date dateParse(String birthDate) {
        SimpleDateFormat dateFromat = new SimpleDateFormat("yyyy-MM-dd");
        Date d = null;
        try {
            d = dateFromat.parse(birthDate);
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(AdminProfileEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
        return d;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonEditPhoto;
    private javax.swing.JButton jButtonEditProfile;
    private javax.swing.JComboBox jComboBoxBloodType;
    private com.toedter.calendar.JDateChooser jDateChooserBirthDate;
    private javax.swing.JFileChooser jFileChooserPhoto;
    private javax.swing.JLabel jLabelAdress;
    private javax.swing.JLabel jLabelBirthDate;
    private javax.swing.JLabel jLabelCC;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelInformation;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNationality;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelProfile;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLabelwallpaper;
    private javax.swing.JPanel jPanelInformation;
    private javax.swing.JPanel jPanelWallpaper;
    private javax.swing.JTextField jTextFieldAdress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldNCC;
    private javax.swing.JTextField jTextFieldNTel;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNationality;
    // End of variables declaration//GEN-END:variables
}
