/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.dainamic.nepum.ui.hp.patients;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import pt.dainamic.nepum.model.Patient;
import pt.dainamic.nepum.ui.hp.patients.exercises.PrescribeSession;
import pt.dainamic.nepum.ws.PatientWS;

/**
 *
 * @author jorge
 */
public class PatientProfile extends javax.swing.JFrame {

    private Logger log = Logger.getLogger(PatientProfile.class);
    private Patient p;

    /**
     * Creates new form PatienteProfile
     */
    public PatientProfile(Patient p) {
        initComponents();
        setIcon();
        this.p = p;
        try {
            setFields(p);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(PatientProfile.this,
                    e.getMessage(), "Erro ao carregar os dados do Profissional de Saúde", JOptionPane.ERROR_MESSAGE);
        }
    }

    public PatientProfile() {
    }

    private void setFields(Patient p) {
        this.jTextFieldNamep.setText(p.getName());
        this.jTextFieldLastNamep.setText(p.getLastName());
        this.jTextFieldBirthDate.setText(p.getBirthDate());
        this.jTextFieldNumTelp.setText(String.valueOf(p.getNumTel()));
        this.jTextFieldNationalityp.setText(p.getNationality());
        this.jTextFieldNumCCp.setText(String.valueOf(p.getNumCC()));
        this.jTextFieldEmailp.setText(p.getEmail());
        this.jTextFieldAdressp.setText(p.getAdress());
        this.jTextFieldBloodGroupp.setText(p.getBloodGroup());
        this.jTextFieldDescription.setText(p.getDescription());
        this.jTextField6.setText(p.getGender());
        this.jTextFieldMaritalStatus.setText(p.getMaritalStatus());
        if(p.getNif()!=0){
            this.jTextFieldNIF.setText(String.valueOf(p.getNif()));
        }
        this.jTextFieldPathology.setText(p.getPathology());

        if (p.getPicture().equals("profile")) {
            ImageIcon pic = new ImageIcon(getClass().getResource("/pt/dainamic/nepum/images/pics/profile.PNG"));
            jLabelPhoto.setIcon(new ImageIcon(pic.getImage().getScaledInstance(
                    jLabelPhoto.getWidth(), jLabelPhoto.getHeight(), Image.SCALE_DEFAULT)));
        } else {
            jLabelPhoto.setIcon(new ImageIcon(getImageFromServer(p.getPicture(), 90, 90)));
        }
    }
 private void setIcon(){
        List<Image> icons = new ArrayList<>();
        icons.add(new ImageIcon(getClass().getResource("/pt/dainamic/nepum/images/logo.png")).getImage());
        icons.add(new ImageIcon(getClass().getResource("/pt/dainamic/nepum/images/logo-icon.png")).getImage());
        setIconImages(icons);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWallpaper = new javax.swing.JPanel();
        jPanelInformation = new javax.swing.JPanel();
        jLabelHealthPatientProfile = new javax.swing.JLabel();
        jLabelPhoto = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelBirthDate = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jLabelCC = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelNationality = new javax.swing.JLabel();
        jLabelAdress = new javax.swing.JLabel();
        jLabelNIF = new javax.swing.JLabel();
        jLabelMaritalStatus = new javax.swing.JLabel();
        jLabelPathology = new javax.swing.JLabel();
        jLabelBloodType = new javax.swing.JLabel();
        jTextFieldPathology = new javax.swing.JTextField();
        jTextFieldMaritalStatus = new javax.swing.JTextField();
        jTextFieldAdressp = new javax.swing.JTextField();
        jTextFieldNationalityp = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextFieldLastNamep = new javax.swing.JTextField();
        jTextFieldDescription = new javax.swing.JTextField();
        jTextFieldBloodGroupp = new javax.swing.JTextField();
        jTextFieldNIF = new javax.swing.JTextField();
        jTextFieldEmailp = new javax.swing.JTextField();
        jTextFieldNumCCp = new javax.swing.JTextField();
        jTextFieldNumTelp = new javax.swing.JTextField();
        jTextFieldBirthDate = new javax.swing.JTextField();
        jTextFieldNamep = new javax.swing.JTextField();
        jButtonPrescribeSession = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonGenerateReport = new javax.swing.JButton();
        jLabelDiscription = new javax.swing.JLabel();
        jLabelInformation = new javax.swing.JLabel();
        jLabelwallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(705, 520));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelWallpaper.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanelWallpaper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInformation.setMaximumSize(new java.awt.Dimension(680, 380));
        jPanelInformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHealthPatientProfile.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelHealthPatientProfile.setText("Paciente");
        jPanelInformation.add(jLabelHealthPatientProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabelPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/dainamic/nepum/images/pics/profile.PNG"))); // NOI18N
        jPanelInformation.add(jLabelPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 90));

        jLabelName.setText("Nome:");
        jPanelInformation.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 49, -1, 20));

        jLabelBirthDate.setText("Data de nascimento:");
        jPanelInformation.add(jLabelBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 79, -1, 20));

        jLabelTel.setText("Nº Tel:");
        jPanelInformation.add(jLabelTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 109, -1, 20));

        jLabelCC.setText(" Nº CC:");
        jPanelInformation.add(jLabelCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 169, -1, 20));

        jLabelEmail.setText("Email:");
        jPanelInformation.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 169, -1, 20));

        jLabelLastName.setText("Apelido:");
        jPanelInformation.add(jLabelLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 55, -1, -1));

        jLabelGender.setText("Sexo:");
        jPanelInformation.add(jLabelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 79, -1, 20));

        jLabelNationality.setText("Nacionalidade:");
        jPanelInformation.add(jLabelNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 109, -1, 20));

        jLabelAdress.setText("Morada:");
        jPanelInformation.add(jLabelAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 139, -1, 20));

        jLabelNIF.setText("  NIF:");
        jPanelInformation.add(jLabelNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 199, 30, 20));

        jLabelMaritalStatus.setText(" Estado Civil:");
        jPanelInformation.add(jLabelMaritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 199, -1, 20));

        jLabelPathology.setText(" Patologia:");
        jPanelInformation.add(jLabelPathology, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 229, -1, 20));

        jLabelBloodType.setText("    Grupo sanguíneo:");
        jPanelInformation.add(jLabelBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 229, -1, 20));

        jTextFieldPathology.setEditable(false);
        jPanelInformation.add(jTextFieldPathology, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 140, -1));

        jTextFieldMaritalStatus.setEditable(false);
        jPanelInformation.add(jTextFieldMaritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 140, -1));

        jTextFieldAdressp.setEditable(false);
        jPanelInformation.add(jTextFieldAdressp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 400, -1));

        jTextFieldNationalityp.setEditable(false);
        jPanelInformation.add(jTextFieldNationalityp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 140, -1));

        jTextField6.setEditable(false);
        jPanelInformation.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 140, -1));

        jTextFieldLastNamep.setEditable(false);
        jPanelInformation.add(jTextFieldLastNamep, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 140, -1));

        jTextFieldDescription.setEditable(false);
        jPanelInformation.add(jTextFieldDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 310, 50));

        jTextFieldBloodGroupp.setEditable(false);
        jPanelInformation.add(jTextFieldBloodGroupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 60, -1));

        jTextFieldNIF.setEditable(false);
        jPanelInformation.add(jTextFieldNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 150, -1));

        jTextFieldEmailp.setEditable(false);
        jPanelInformation.add(jTextFieldEmailp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 150, -1));

        jTextFieldNumCCp.setEditable(false);
        jPanelInformation.add(jTextFieldNumCCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 140, -1));

        jTextFieldNumTelp.setEditable(false);
        jPanelInformation.add(jTextFieldNumTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 150, -1));

        jTextFieldBirthDate.setEditable(false);
        jPanelInformation.add(jTextFieldBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 150, -1));

        jTextFieldNamep.setEditable(false);
        jPanelInformation.add(jTextFieldNamep, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 150, -1));

        jButtonPrescribeSession.setText("Prescrever sessão");
        jButtonPrescribeSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrescribeSessionActionPerformed(evt);
            }
        });
        jPanelInformation.add(jButtonPrescribeSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jButtonBack.setText("Voltar");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanelInformation.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        jButtonDelete.setText("Eliminar Paciente");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanelInformation.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        jButtonGenerateReport.setText("Gerar relatório");
        jPanelInformation.add(jButtonGenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jLabelDiscription.setText("  Descrição:");
        jPanelInformation.add(jLabelDiscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 259, -1, 20));

        jLabelInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/dainamic/nepum/images/backGround/second.jpg"))); // NOI18N
        jLabelInformation.setMaximumSize(new java.awt.Dimension(680, 380));
        jLabelInformation.setMinimumSize(new java.awt.Dimension(680, 380));
        jLabelInformation.setPreferredSize(new java.awt.Dimension(680, 380));
        jPanelInformation.add(jLabelInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelWallpaper.add(jPanelInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 680, 380));

        jLabelwallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/dainamic/nepum/images/backGround/first.jpg"))); // NOI18N
        jPanelWallpaper.add(jLabelwallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        getContentPane().add(jPanelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrescribeSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrescribeSessionActionPerformed
        //por id Terapeuta!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        new PrescribeSession(p, 1).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonPrescribeSessionActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        new PatientsList().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed


    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        try {
            PatientWS pWS = new PatientWS();
            pWS.deletePatient(p.getIdPatient());
            new PatientsList().setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(PatientProfile.this,
                    e.getMessage(), "Erro ao eliminar o Paciente", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonGenerateReport;
    private javax.swing.JButton jButtonPrescribeSession;
    private javax.swing.JLabel jLabelAdress;
    private javax.swing.JLabel jLabelBirthDate;
    private javax.swing.JLabel jLabelBloodType;
    private javax.swing.JLabel jLabelCC;
    private javax.swing.JLabel jLabelDiscription;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelHealthPatientProfile;
    private javax.swing.JLabel jLabelInformation;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelMaritalStatus;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNationality;
    private javax.swing.JLabel jLabelPathology;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLabelwallpaper;
    private javax.swing.JPanel jPanelInformation;
    private javax.swing.JPanel jPanelWallpaper;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldAdressp;
    private javax.swing.JTextField jTextFieldBirthDate;
    private javax.swing.JTextField jTextFieldBloodGroupp;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldEmailp;
    private javax.swing.JTextField jTextFieldLastNamep;
    private javax.swing.JTextField jTextFieldMaritalStatus;
    private javax.swing.JTextField jTextFieldNIF;
    private javax.swing.JTextField jTextFieldNamep;
    private javax.swing.JTextField jTextFieldNationalityp;
    private javax.swing.JTextField jTextFieldNumCCp;
    private javax.swing.JTextField jTextFieldNumTelp;
    private javax.swing.JTextField jTextFieldPathology;
    // End of variables declaration//GEN-END:variables

    private Image getImageFromServer(String picture, int with, int heigth) {
        try {
             URL url = new URL(picture.trim());
             log.debug("\n\tProfile Image: " + url.toString());
            BufferedImage image = ImageIO.read(url);
            ImageIcon pic = new ImageIcon(image);
            return pic.getImage().getScaledInstance(with, heigth, Image.SCALE_DEFAULT);
        } catch (MalformedURLException ex) {
            log.error(ex.getMessage());
            throw new RuntimeException("Erro ao carregar imagem");
        } catch (IOException ex) {
            log.error(ex.getMessage());
            throw new RuntimeException("Erro ao carregar imagem");
        }
    }

}
