/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.dainamic.nepum.ui.login;

import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import pt.dainamic.nepum.ws.LoginWS;

/**
 *
 * @author Jorge_2
 */
public class ForgetPassword extends javax.swing.JFrame {

    private LoginWS lWS;
    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword() {
        initComponents();
        lWS = new LoginWS();
    }
    
     private void numberConsume(KeyEvent evt) {
        String numbers = "0123456789";
        if (numbers.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEmail = new javax.swing.JLabel();
        jLabelCC = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonRecover = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jTextFieldCC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 160));
        setMinimumSize(new java.awt.Dimension(300, 160));
        setPreferredSize(new java.awt.Dimension(300, 160));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmail.setText("Email:");
        getContentPane().add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelCC.setText("Nº CC:");
        getContentPane().add(jLabelCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 10, 190, -1));

        jButtonRecover.setText("Recuperar");
        jButtonRecover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecoverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRecover, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jButtonBack.setText("Cancelar");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 80, -1));

        jTextFieldCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCCKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/dainamic/nepum/images/backGround/second.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 363, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonRecoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecoverActionPerformed
        // TODO add your handling code here:
        Component frame = null; 
        if(jTextFieldEmail.getText().isEmpty() || jTextFieldCC.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Aviso", JOptionPane.INFORMATION_MESSAGE);  
        }
        
        else if(jTextFieldCC.getText().trim().length() != 8){
          JOptionPane.showMessageDialog(null, "O NºCC deve ter 8 digitos!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
         
        }else{ 
        String email = jTextFieldEmail.getText().trim();
        int nCC = Integer.parseInt(jTextFieldCC.getText().trim());
        lWS.getPassword(email, nCC);
        JOptionPane.showMessageDialog(null, "A sua password será enviada para o respectivo email", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        dispose();
        }
        
        
    }//GEN-LAST:event_jButtonRecoverActionPerformed
    
    private void jTextFieldCCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCCKeyTyped
    
    }//GEN-LAST:event_jTextFieldCCKeyTyped
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ForgetPassword().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonRecover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCC;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JTextField jTextFieldCC;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables
}
